parser: "@typescript-eslint/parser"

parserOptions:
  project: 'tsconfig.json'
  tsconfigRootDir: '.'

plugins:
  - "@typescript-eslint"
  - prettier
  - standard
  - jest

extends:
  - standard
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
  - prettier/standard
  - prettier/@typescript-eslint

rules:
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-unused-vars": off

env:
  "jest/globals": true
