image: node:alpine

stages:
  - install
  - test
  - build

Install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules 
  cache:
    paths:
      - node_modules

Lint:
  stage: test
  script:
    - npm run lint

Typecheck:
  stage: test
  script:
    - npm run typecheck

Test:
  stage: test
  script:
    - npm run test

Build:
  stage: build
  script:
    - npm run build
