image: node:alpine

stages:
  - install
  - test
  - build

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules 
  cache:
    paths:
      - node_modules

lint:
  stage: test
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
